/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package artigui;

import javax.swing.*;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.awt.color.*;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
public class App
{
    public static void main(String[] args)
    {
        var frame = new JFrame("Artigiano Bot: Scan Stanza");
        frame.setSize(new Dimension(800,600));

        //PANELLO BOTTONI
        var panello_bottoni = new JPanel();
        panello_bottoni.setLayout(new GridBagLayout());
        var bottone_start = new JButton("Inizia Scansione");
        var bottone_stop = new JButton("Ferma Scansione");
        panello_bottoni.add(bottone_start);
        panello_bottoni.add(bottone_stop);



        bottone_start.addActionListener(e -> 
        {
            System.out.println("Bottone Premuto!");
            try {
                Thread thread = new Thread(() -> {
                    System.out.println("Thread creato");
                });
                thread.start();
                Runtime.getRuntime().exec("sweethome3d");

            } catch (IOException e1) {
                e1.printStackTrace();
                System.out.println("Errore IO");
            }
        });
        
        var panello_stanza = new JPanel();
        panello_stanza.add(new JLabel("Modelli 3D"));
        panello_stanza.setBackground(new Color(15,15,15));

        frame.setLayout(new BoxLayout(frame.getContentPane(),BoxLayout.Y_AXIS));
        frame.add(panello_bottoni);
        frame.add(panello_stanza);
        frame.setVisible(true);
    }
}
